### ISSUE TITLE
[AWS Developer] Course Project. Migration from Serverless to AWS SDK

### ISSUE THREAD

**Issue by dzmitry-varabei** [rolling-scopes-school/aws#6]
1) Copy the project description and it's material from 
https://github.com/EPAM-JS-Competency-center/cloud-development-course-initial to our repository
2) Create a list of required AWS services (S3, SQS, etc.)

**Comment by dzmitry-varabei** [comment]
3. Refactor front-end

**Comment by ThorsAngerVaNeT** [comment]
1. Course copied to [nodejs-aws branch](https://github.com/rolling-scopes-school/aws/tree/nodejs-aws)

**Comment by ThorsAngerVaNeT** [comment]
Also forked Cart API Service and update it.
Migrate all task to AWS CDK.
Issue could be closed

**Comment by dzmitry-varabei** [comment]
@ThorsAngerVaNeT Thanks a ton! Great job!
